name: Unit Testing

on:
  push:
    branches:
      - development
      - staging
      - beta
      - release
      - master
      - 'feature-*'
  pull_request:
    branches:
      - development
      - staging
      - beta
      - release
      - master
      - 'feature-*'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Running unit tests
        run: yarn test:coverage
